service:
  name: user-api-service

# Add the serverless-webpack plugin
plugins:
  - serverless-webpack
  - serverless-reqvalidator-plugin
  - serverless-aws-documentation
  - serverless-jest-plugin

provider:
  name: aws
  runtime: nodejs8.10
  environment:
    DYNAMODB_TABLE: ${self:service}-${opt:stage, self:provider.stage}
    NODE_ENV: ${self:provider.stage}
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: "arn:aws:dynamodb:${opt:region, self:provider.region}:*:table/${self:provider.environment.DYNAMODB_TABLE}"
custom:
  documentation:
    api:
      info:
        version: '1.0.0'
        title: Orange Theory API
        description: Orange Theory API, for User Managnment demo
      tags:
        - name: User
          description: User Management
    models:
      - name: CreateUserRequest
        contentType: "application/json"
        schema: ${file(request_response_models/create_user_request_response_model.json)} # reference to your model's json schema file. You can also declare the model inline.
functions:
  list-users:
    handler: handler.listUsers
    events:
      - http:
          method: get
          path: /
          cors: true
  create-user:
    handler: handler.createUser
    events:
      - http:
          method: post
          path: /
          cors: true
          documentation:
            summary: "Create user"
            description: "Create new user"
            tags:
              - User
            requestModels:
              "application/json": CreateUserRequest
            methodResponses:
              - statusCode: 200
                responseModels:
                  "application/json" : CreateUserRequest
              - statusCode: 400
          reqValidatorName: onlyBody # reference and use the 'only-body' request validator
  update-user:
    handler: handler.updateUser
    events:
      - http:
          method: put
          path: /{email}
          cors: true
  get-user:
    handler: handler.getUser
    events:
      - http:
          method: get
          path: /{email}
          cors: true
  delete-user:
    handler: handler.deleteUser
    events:
      - http:
          method: delete
          path: /{email}
          cors: true

resources:
  Resources:
    UserDynamoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          -
            AttributeName: email
            AttributeType: S
        KeySchema:
          -
            AttributeName: email
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:provider.environment.DYNAMODB_TABLE}
    onlyBody:
      Type: AWS::ApiGateway::RequestValidator
      Properties:
        Name: 'only-body'
        RestApiId:
          Ref: ApiGatewayRestApi
        ValidateRequestBody: true # true or false
        ValidateRequestParameters: false # true or false
